version: '3.7'
services:
    app:
        container_name: container_website
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - '/node_modules'
        ports:
            - '3003:3000'
        environment:
            - NODE_ENV=development