version: '3.7'

services:
  mysql:
    image: mysql
    container_name: bruno_mysql
    #restart: always
    volumes:
      - ./mysql:/var/lib/mysql:z
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3308:3308
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: rootpwd
      NYSQL_DATABASE: bazardb
