version: '3.7'

services:
  app:
    build:  .
    container_name: bruno_node
    command: npm start
    #restart: always
    volumes:
      - .:/usr/app
    ports:
      - 8090:8090
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: rootpwd
      NYSQL_DATABASE: bazardb