version: '3.7'

services:
    node:
      build:  ./
      container_name: bruno_node
      command: npm start
      #restart: always
      volumes:
        - .:/app
      ports:
        - 8090:8090
      depends_on: 
        - mysql


    mysql:
      image: mysql
      #restart: always
      volumes:
        - ./mysql:/var/lib/mysql:z
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - 3308:3308
      environment:
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: rootpwd
        NYSQL_DATABASE: bazardb


